#=========================================
# CodeBuildで設定する環境変数
#=========================================
# S3_BUCKET_PATH
#  → アップロード先のS3バケットを指定する(ex: s3://bucket-name)
version: 0.2

env:
  parameter-store:
    GOOGLE_ANALYTICS_ID: /irad/portfolio/GOOGLE_ANALYTICS_ID
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Build started on `date`
      - npm install -g yarn
      - yarn --version
  build:
    commands:
      - yarn
      - yarn generate
      - aws s3 sync dist $S3_BUCKET_PATH --delete
  post_build:
    commands:
      - echo Build Completed on `date`
